# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_of_existing_checking_account', models.IntegerField(choices=[(0, '... < 0 руб.'), (1, '0 <= ... < 200 руб.'), (2, '... >= 200 руб.'), (3, 'нет счета')], verbose_name='Статус текущего счета')),
                ('credit_history', models.IntegerField(choices=[(0, 'кредиты не брались / все кредиты погашены'), (1, 'все кредиты в нашем банке выплачивались своевременно'), (2, 'текущие кредиты выплачиваются вовремя'), (3, 'имели место несвоевременные выплаты в прошлом'), (4, 'критический аккаунт')], verbose_name='Кредитная история')),
                ('purpose', models.IntegerField(choices=[(0, 'автомобиль (новый)'), (1, 'автомобиль (б/у)'), (2, 'мебель / оборудывание'), (3, 'радио / телевидение'), (4, 'бытовая техника'), (5, 'ремонт'), (6, 'образование'), (7, 'отпуск'), (8, 'переквалификация'), (9, 'бизнес'), (10, 'другое')], verbose_name='Цель')),
                ('present_employment_since', models.IntegerField(choices=[(0, 'безработный'), (1, '... < 1 года'), (2, '1 <= ... < 4 года'), (3, '4 <= ... < 7 лет'), (4, '... >= 7 лет')], verbose_name='Время на текущем месте работы')),
                ('personal_status', models.IntegerField(choices=[(0, 'мужской, разведен'), (1, 'женский, разведена / замужем'), (2, 'мужской, холост'), (3, 'мужской, женат'), (4, 'женский, не замужем')], verbose_name='Семейное положение и пол')),
                ('other_debtors', models.IntegerField(choices=[(0, 'нет'), (1, 'созаявитель'), (2, 'гарант')], verbose_name='Поручители')),
                ('property', models.IntegerField(choices=[(0, 'недвижимость'), (1, 'страхование жизни'), (2, 'автомобиль'), (3, 'нет данных / нет имущества')], verbose_name='Имущество')),
                ('installment_plans', models.IntegerField(choices=[(0, 'банк'), (1, 'магазин'), (2, 'нет')], verbose_name='Другие рассрочки')),
                ('housing', models.IntegerField(choices=[(0, 'съемное'), (1, 'собственное'), (2, 'бесплатное')], verbose_name='Жилье')),
                ('job', models.IntegerField(choices=[(0, 'безработный / неквалифицированный - нерезидент'), (1, 'неквалифицированный - резидент'), (2, 'квалифицированный'), (3, 'менеджмент / высококвалифицированный')], verbose_name='Тип занятости')),
                ('telephone', models.IntegerField(choices=[(0, 'нет'), (1, 'есть')], verbose_name='Телефон')),
                ('foreign_worker', models.IntegerField(choices=[(0, 'да'), (1, 'нет')], verbose_name='Иностранный работник')),
                ('credit_amount', models.IntegerField()),
                ('request_id', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('duration_in_month', models.IntegerField()),
            ],
        ),
    ]
